spring:
  datasource:
   url: jdbc:mariadb://localhost:3306/spring_boot_example
   username: root
   password: test
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true